# Generated by Django 4.0.4 on 2022-09-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=30)),
                ('gmail', models.TextField()),
                ('password', models.TextField(max_length=100)),
                ('orders', models.TextField()),
                ('cart', models.TextField()),
            ],
        ),
    ]
