# Generated by Django 4.0.4 on 2022-09-06 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0002_products_alter_user_cart_alter_user_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
