# Generated by Django 4.0.4 on 2022-09-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0004_alter_product_prod_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='product',
            name='prod_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
