# Generated by Django 4.0.4 on 2022-09-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0005_remove_product_id_product_prod_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_id',
            field=models.IntegerField(default=1),
        ),
    ]
