# Generated by Django 4.0.4 on 2022-09-07 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0006_product_id_alter_product_prod_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prod_id',
        ),
    ]
