# Generated by Django 4.0.4 on 2022-09-07 05:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0008_remove_product_id_product_prod_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_id',
            field=models.IntegerField(default=uuid.uuid1, primary_key=True, serialize=False, unique=True),
        ),
    ]
