# Generated by Django 4.0.4 on 2022-09-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0010_remove_product_prod_id_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('prod_id', models.IntegerField(default=1, primary_key=True, serialize=False, unique=True)),
                ('prod_img', models.TextField()),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('stock', models.IntegerField(default=10)),
                ('price', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
