# Generated by Django 4.0.4 on 2022-09-07 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0011_box_delete_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Box',
            new_name='Product',
        ),
    ]
