# Generated by Django 4.0.4 on 2022-09-07 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0013_product_id_alter_product_prod_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prod_id',
            new_name='prod_pehchan',
        ),
    ]
