# Generated by Django 4.0.4 on 2022-09-07 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0014_rename_prod_id_product_prod_pehchan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prod_pehchan',
            new_name='prod_id',
        ),
    ]
